#!/bin/bash

log() {
  echo $1
}

config_path="${HOME}/.config/kdrive-auto-update" 

architecture=$(cat $config_path/architecture)
latest=$(curl -s https://www.infomaniak.com/drive/latest | jq ".\"$architecture\"")

autostart_path="${HOME}/.config/autostart" 
desktopfile="$autostart_path/kDrive.desktop"

exec_path="${HOME}/.local/bin"

mkdir -p "$autostart_path"
mkdir -p "$exec_path"

if echo "$latest" | jq -e '.version' > /dev/null; then
  latest_version=$(echo "$latest" | jq -r ".version")
  else
  log "unable to get latest version"
  exit 1
fi

actual_version=$(cat $desktopfile | grep Version | cut -d'=' -f2)

log "actual_version: $actual_version"
log "latest_version: $latest_version"

if [ "$actual_version" = "$latest_version" ]; then
  log "no update needed"
  exit 0
fi

log "update needed"

downloadurl=$(echo "$latest" | jq -r ".downloadurl")
exec_file="$exec_path/kDrive-$architecture-v$latest_version.AppImage"

wget -O "$exec_file"  "$downloadurl"
chmod +x "$exec_file"

histo=2
log "remove old execution files omit last $histo files"
for delete_file in `find "$exec_path" -type f -name kDrive-$architecture-v*.AppImage | sort -r | tail -n +$((histo + 1))`
do
  log "old version finded : $delete_file"
  rm "$delete_file"
done


log "add desktop file in $desktopfile"
echo "[Desktop Entry]
Name=kDrive
GenericName=File Synchronizer
Exec='${exec_file}'
Version=${latest_version}
Terminal=false
Icon=kdrive
Categories=Network
Type=Application
StartupNotify=false
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=10" > $desktopfile
chmod +x $desktopfile