#!/bin/bash

log() {
  now="$(date +%F) $(date +"%T")"
  echo "$now: $1"
  echo "$now: $1" >> /var/tmp/kdrive-auto-update.log
}

config_path="${HOME}/.config/kdrive-auto-update" 

architecture=$(cat $config_path/architecture)
latest=$(curl -s https://www.infomaniak.com/drive/latest | jq ".\"$architecture\"")
latest_version=$(echo "$latest" | jq -r ".version")
actual_version=$(cat $config_path/actual_version 2>/dev/null)


D='0|[1-9][0-9]*'
if ! [[ "$latest_version" =~ ^($D)\.($D)\.($D)\.($D)$ ]]; then
  log "unable to get latest version"
  exit 1
fi

autostart_path="${HOME}/.config/autostart" 
desktopfile="$autostart_path/kDrive.desktop"

exec_path="${HOME}/.local/bin"

mkdir -p "$autostart_path"
mkdir -p "$exec_path"

log "actual_version: $actual_version"
log "latest_version: $latest_version"

if [ "$actual_version" = "$latest_version" ]; then
  log "no update needed"
  exit 0
fi

log "update needed"

downloadurl=$(echo "$latest" | jq -r ".downloadurl")
exec_file="$exec_path/kDrive-$architecture-v$latest_version.AppImage"

wget -O "$exec_file"  "$downloadurl"
chmod +x "$exec_file"

histo=3
log "remove old execution files omit last $histo files"
for delete_file in `find "$exec_path" -type f -name kDrive-$architecture-v*.AppImage | sort -r | tail -n +$((histo + 1))`
do
  log "old version finded : $delete_file"
  rm "$delete_file"
done


log "add desktop file in $desktopfile"

desktopfilecontent=$(sed '/^Exec=/d' $desktopfile)

echo "$desktopfilecontent
Exec='${exec_file}'
" > $desktopfile
chmod +x $desktopfile

log "save actual version"
echo "$latest_version" > $config_path/actual_version